#!/usr/bin/env python3
"""Generate supplemental Google domains and Google service IP rules.

Google documents this address-set difference at:
https://docs.cloud.google.com/vpc/docs/access-apis-external-ip
"""

import argparse
import ipaddress
import json
from pathlib import Path
from urllib.request import urlopen


GOOG_URL = "https://www.gstatic.com/ipranges/goog.json"
CLOUD_URL = "https://www.gstatic.com/ipranges/cloud.json"
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "Google.list"
DOMAIN_SUFFIXES = ("goog", "google", "ggpht.com", "gvt1.com", "gvt2.com", "pkg.dev")


def read_feed(url, file_path):
    if file_path is not None:
        return json.loads(file_path.read_text(encoding="utf-8"))
    with urlopen(url, timeout=30) as response:
        return json.load(response)


def networks(feed, version):
    key = "ipv4Prefix" if version == 4 else "ipv6Prefix"
    return list(ipaddress.collapse_addresses(
        ipaddress.ip_network(prefix[key])
        for prefix in feed["prefixes"] if key in prefix
    ))


def service_networks(goog, cloud):
    result = []
    for version in (4, 6):
        remaining = networks(goog, version)
        for excluded in networks(cloud, version):
            updated = []
            for network in remaining:
                if network.subnet_of(excluded):
                    continue
                if excluded.subnet_of(network):
                    updated.extend(network.address_exclude(excluded))
                else:
                    updated.append(network)
            remaining = updated
        result.extend(ipaddress.collapse_addresses(remaining))
    return result


def render(goog, cloud, ranges):
    lines = [
        "# Supplemental Google domains and Google API/service IP ranges.",
        "# Generated by script/update_google_rules.py; Google Cloud customer IPs excluded.",
        "# Guidance: https://docs.cloud.google.com/vpc/docs/access-apis-external-ip",
        f"# Google source: {GOOG_URL}",
        f"# Google creationTime: {goog['creationTime']}",
        f"# Cloud source: {CLOUD_URL}",
        f"# Cloud creationTime: {cloud['creationTime']}",
    ]
    lines.extend(["", "# Supplemental domains"])
    lines.extend(f"DOMAIN-SUFFIX,{suffix}" for suffix in DOMAIN_SUFFIXES)
    lines.extend(["", "# Google service IP ranges (goog.json - cloud.json)"])
    lines.extend(
        f"{'IP-CIDR' if network.version == 4 else 'IP-CIDR6'},{network},no-resolve"
        for network in ranges
    )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--goog-file", type=Path, help="Offline goog.json snapshot")
    parser.add_argument("--cloud-file", type=Path, help="Offline cloud.json snapshot")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if (args.goog_file is None) != (args.cloud_file is None):
        parser.error("--goog-file and --cloud-file must be supplied together")

    try:
        goog = read_feed(GOOG_URL, args.goog_file)
        cloud = read_feed(CLOUD_URL, args.cloud_file)
        ranges = service_networks(goog, cloud)
        if not ranges:
            raise ValueError("Google service IP ranges are empty")
        args.output.write_text(render(goog, cloud, ranges), encoding="utf-8")
    except (OSError, ValueError, KeyError, TypeError) as exc:
        parser.exit(1, f"Failed to generate Google rules: {exc}\n")
    print(f"Wrote {len(DOMAIN_SUFFIXES)} domain rules and {len(ranges)} IP rules to {args.output}")


if __name__ == "__main__":
    main()
